remote_theme: b2a3e8/jekyll-theme-console-light
header_pages:
  - index.md
  - about.md
style: light # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true
footer: 'follow us on <a href="https://twitter.com/">twitter</a>'
